package oop.day5.thread;

public class ResultTask  extends Thread {
    public void run(){
        System.out.println("Result generated by: " +
                Thread.currentThread().getName());

    }

    public static void main(String[] args) {
        ResultTask t1 = new ResultTask();
        t1.run(); // ℹ️ normal execution -> always the main thread
        t1.start(); // 🟢multi threading -> T-0, T-1 and so on, it always start with 0
        // start() internally calls run()
        // Thread cannot be started twice
    }
}
